### ISSUE TITLE
Is the change feed reliable?

### ISSUE THREAD

**Issue by murraybauer** [WeWatchWall/stark-db#1]
The changes seem to be captured via a database trigger which happens after say and insert or update.
https://github.com/WeWatchWall/stark-db/blob/f0924b6e9ce7acfc0148d0c5336fb7360cc69066/src/utils/queries.ts#L195

Database tirggers are not guarentted to trigger in a transaction/atomically - leading to lost updates.
https://stackoverflow.com/questions/72300628/are-sqlite-triggers-guaranteed-to-always-be-executed-with-their-corresponding-tr

You'd be better off modifying the insert to transcationally write to both tables like in the outbox pattern.
https://microservices.io/patterns/data/transactional-outbox.html

**Comment by adrian-burlacu-software** [comment]
@murraybauer 
FIY: https://sqlite.org/forum/info/2a650a70a6136537fa2d08789b63f1863ad28a55b871a7e7e9564664c8c7a87e
